name: Windows Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests psutil pyinstaller tk
        pip install git+https://github.com/naoyuki2006/tkinterhtml

    - name: Build executable
      run: |
        pyinstaller --onefile main_script.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: script-executable
        path: dist/main_script.exe
