name: Python Script Packaging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --noconsole --icon=https://www.xmg888.top/assets/static/general/image/2024-07-29/658f69255cf6ee4adefa2a1740e2992c.png kop.py

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: script-executable
          path: dist/kop.exe
