name: 无尽接码 - Package Python Script

on:
  push:
    branches:
      - main  # 可根据需求修改分支名称

jobs:
  build:
    runs-on: windows-latest  # 选择 Windows 系统进行打包，因为要生成 .exe 文件

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # 可根据你的 Python 版本修改

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests PyQt5

      - name: Package script
        run: pyinstaller --onefile --windowed --name 无尽接码 sms_verification_code_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 无尽接码-packaged-app
          path: dist/无尽接码.exe
    
